
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://www.comans.be"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /personal-jekyll-theme
baseurl: ""

# Google tracking id to track your visitors

#google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

#force-https: True

markdown: kramdown

#############
# HTML Head #
#############

lang: "en"
author: "Jan Comans"
title: "{ Jan Comans }"
description: "Blog and website of Jan Comans, blogging mainly for tech. Opinions expressed are mine."
keywords: "jan, comans, personal, business"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/background.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 3500
lines: # You can add HTML Tags in the Text

    - text: "Beautiful is better than ugly."
    - text: "Explicit is better than implicit."
    - text: "Simple is better than complex."
    - text: "Complex is better than complicated."
    - text: "Flat is better than nested."
    - text: "Sparse is better than dense."
    - text: "Readability counts."
    - text: "Special cases aren't special enough to break the rules."
    - text: "Although practicality beats purity."
    - text: "Errors should never pass silently."
    - text: "Unless explicitly silenced."
    - text: "In the face of ambiguity, refuse the temptation to guess."
    - text: "There should be one-- and preferably only one --obvious way to do it."
    - text: "Although that way may not be obvious at first unless you're Dutch."
    - text: "Now is better than never."
    - text: "Although never is often better than *right* now."
    - text: "If the implementation is hard to explain, it's a bad idea."
    - text: "If the implementation is easy to explain, it may be a good idea."
    - text: "Namespaces are one honking great idea -- let's do more of those!"

me-img: "/img/mugshot.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
#pocket-share: True
#vkontakte-share: True

#disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:

  - image: "/img/timeline/tudelft.png"
    date: "Jun 2016 - Present"
    description: "Finishing PhD Thesis Writing"

  - image: "/img/timeline/LM.png"
    date: "Dec 2014 - May 2016"
    description: "Lockheed Martin Commercial Flight Training"

  - image: "/img/timeline/tudelft.png"
    date: "Aug 2009 - Nov 2014"
    description: "PhD Aerospace Engineering"
  
  - image: "/img/timeline/tudelft.png"
    date: "Sep 2002 - Jul 2009"
    description: "Studying Aerospace Engineering"

  



# First image of the Timeline

timeline-img: "/img/timeline/young-mugshot.jpg"

###########
# Contact #
###########

email: "jan@comans.be"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://nl.linkedin.com/in/jan-comans-89659b13"
  - title: "facebook"
    url: "https://facebook.com/jancomans"
  - title: "google-plus"
    url: "https://plus.google.com/102074366036110280261"
  - title: "github"
    url: "https://github.com/jcomans"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
