# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: comans.be
email: info -at- comans.be
description: > # this means to ignore newlines until "baseurl:"
  A simple test for now
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jcomans.github.io" # the base hostname & protocol for your site
github_username:  jcomans

# Build settings
markdown: kramdown
